name: Schema Checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  schema-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Introspect schema
        run: |
          docker-compose up -d
          npm i
          npx -y grafbase introspect --dev > sdl.graphql
          echo "type Query {}" >> sdl.graphql

      - uses: grafbase/schema-check-action@v1
        with:
          grafbase-access-token: ${{ secrets.GRAFBASE_ACCESS_TOKEN }}
          project-ref: tomhoule/schema-check-action-single-graph-example@main
          schema-path: ./sdl.graphql
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
