name: Schema Checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  schema-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          docker-compose up -d
          npm i
          npx -y grafbase introspect --dev > sdl.graphql

      - uses: grafbase/schema-check-action@main
        with:
          grafbase_access_token: ${{ secrets.GRAFBASE_ACCESS_TOKEN }}
          project_ref: tomhoule/schema-check-action-single-graph-example@main
          schema_path: ./sdl.graphql
